before_script:
- export NVM_DIR=/usr/local/nvm
- export NVM_NODE_VERSION=6.9.1
- export PATH=$NVM_DIR/versions/node/v$NVM_NODE_VERSION/bin:$PATH
- export DISPLAY=:99

stages:
  - flash

flash_binary:
  image: philcryer/min-jessie
  stage: flash
  only:
  - master
  script:
  - apt-get install curl
  - curl -sL https://deb.nodesource.com/setup_6.x | bash -
  - apt-get install -y nodejs
  - npm install npm --global
  - node --version
  - npm --version
  - npm install -g particle-cli
