before_script:
- export NVM_DIR=/usr/local/nvm
- export NVM_NODE_VERSION=6.9.1
- export PATH=$NVM_DIR/versions/node/v$NVM_NODE_VERSION/bin:$PATH
- export DISPLAY=:99

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - flash

flash_binary:
  image: node:7
  stage: flash
  only:
  - master
  script:
  - apt-get update
  - apt-get -y install curl
  - curl -sL https://deb.nodesource.com/setup_7.x | bash -
  - apt-get install -y nodejs
  - npm install npm
  - node --version
  - npm --version
  - npm install -g particle-cli
  - particle -q login -u $PARTICLE_USR -p  $PARTICLE_PWD
  - particle compile photon --target 0.7.0
