stages:
  - flash


flash_binary:
  image: philcryer/min-jessie
  stage: flash
  only:
  - master
  script:
  - apt-get install nodejs
  - apt-get install build-essential
  - node --version
  - npm --version
  - npm install -g particle-cli
